### ISSUE TITLE
connecting problems

### ISSUE THREAD

**Issue by djepsylon** [vr6syncro/Bambulab_Esp32_LEDController#10]
is your firmare fully functionnal with last firmwares of x1c?
my esp can't connect fully to all functions, i v only wifi and ams status working
![vivaldi_CcCE2Xc2jW](https://github.com/user-attachments/assets/763775b6-e12a-4abe-9da0-33427aa44241)

**Comment by vr6syncro** [comment]
Hi, I can't tell you at the moment. My printer is not on the latest firmware. But I haven't heard that they've changed anything there either. It "should" at least work.

Are the LEDs working as they should?

Do the problems only occur with the web interface?

What do the debug outputs say? Connect the controller to the serial console and activate the debug mode with "debug on"

Do the mqtt messages arrive?

You can try to see if the data is displayed on the obs website. To do this, enter /obs after the ip.

You can also check whether there are any errors in the browser.

Usually open with F12.

**Comment by djepsylon** [comment]
hi, i ve found the problem, it was a firewall exception, i ve autorized the ip in my box and all works fine. sorry for loosing time. i think my operator have maked an update on the box who changed some firewall paramaters.

**Comment by vr6syncro** [comment]
hi, no problem. nice to hear that it works now.
