### ISSUE TITLE
Your ESP8266 board is not supported.

### ISSUE THREAD

**Issue by PrintModz** [vr6syncro/Bambulab_Esp32_LEDController#2]
Hey,
die obige Meldung sagt alles, denn ich habe mir extra gestern 3 neue ESP8266 gekauft, welche jedoch nicht mit dem Flasher funktionieren. Erkannt werden diese zwar, jedoch ist ein Flashvorgang nicht möglich.

Wie kann ich sonst noch die Dateien auf den ESP bekommen?

Grüße

**Comment by vr6syncro** [comment]
Hey, es wird nur der EP32 Supportet.
