### ISSUE TITLE
Einige Fragen zum System

### ISSUE THREAD

**Issue by PrintModz** [vr6syncro/Bambulab_Esp32_LEDController#3]
Da ich nun den korrekten ESP habe und die Installation sowie Einrichtung funktioniert hat, stellen sich mir jedoch ein paar Fragen:

- Warum kann das Interface nicht aufgerufen werden, wenn die Installation funktioniert hat?
- Warum versucht er ständig mit dem MQTT zu verbinden? 
- Was ist, wenn ich kein MQTT habe, ist das System dann unbrauchbar?
- Wo finde ich eine genaue Anleitung zum anschließen der PINS? Denn bei mir funktioniert es nicht und die Boards sind ja auch unterschiedlich?
- Warum soll die Seriennummer eingegeben werden? Ich habe es mal gemacht, werde mich da aber mit BambuLab in Verbindung setzen was das für Auswirkungen haben kann?
- Im Moment leider unbrauchbar, da es nicht funktioniert, wobei ich es mir schon gut vorstellen könnte, sollte es funktionieren.

viele Grüße

**Comment by vr6syncro** [comment]
Hi, ich fange mal an das punkt für punkt abzuarbeiten:

-  Das Interface kann nicht aufgerufen werden wenn der ESP32 noch nicht vollständig intialisiert hat oder da was nicht passt.

-  Das ständige verbinden zeigt das dein MQTT Server (Das ist der 3D Drucker selber) nicht erreichbar ist und das der EPS32 die Verbindung aufbauen will.
- Solange du einen Bambulab Drucker hast hast du automatisch MQTT.
- Die ESP32 Boards sind von Hersteller zu Hersteller und von Revision zu Revision doch recht unterschiedlich. Man muss nun wissen was genau man für ein Board hat und googlet (Bildersuche) dann nach dem Boardnamen und zusätzlich den Begriff Pinout. Meistens kommt ziemlich vorne das passende. Oder man geht direkt zum Hersteller und nimmt das aus den technischen Daten. In der Software ist der PIN 16 für die LED Datenleitung hinterlegt. 5V und Masse sollten für jeden machbar sein denke ich.
-  Die Seriennummer benötigt der ESP32 für die MQTT Nachricht damit er auf die richtige Topic hört.
-  Nicht funktioniert ist zu allgemein gehalten um dir weiterhelfen zu können.

**Comment by PrintModz** [comment]
Hey,
Danke für die Antworten, aber ich merke schon, dass das System für mich zu hoch ist.
Habe zwei identische ESP32 bei denen auch das Webinterface funktioniert, wobei es da reine Glückssache ist. 
Denn auf dem einen ESP funktioniert es und auf dem anderen nicht. Auch funktionieren die LED´s nur einen ESP32 und nicht auf beide gleichzeitig, obwohl alle beiden die selbe Verkabelung haben. 

Aber solange das Interface funktioniert und ich die Daten auf OBS anzeigen lassen kann, ist mir das recht. Interessant wäre noch, wenn man die OBS Infos noch selber anpassen könnte. ;)

Grüße

**Comment by vr6syncro** [comment]
kannst du wenn du dir den code selber umschreibst ;)

hast du das szenario in den config richtig gesetzt?
normalerweise sollte das momentan super laufen.
