### ISSUE TITLE
Wiring plan esp 32 s2 mini

### ISSUE THREAD

**Issue by BoraSchninsky** [vr6syncro/Bambulab_Esp32_LEDController#5]
Hi can you upload a short handwritten wiring plan for the connection?

Can I use the esp32 s2 mini module?

I have it flashed with lolin and d1mini bin but nothing work's..

Thank you

![1884809615-261792114 (1)](https://github.com/vr6syncro/Bambulab_Esp32_LEDController/assets/49289734/17b5a70c-81a7-4bee-a378-00d9bcdd9c17)

Based on ESP32-S2FN4R2 WIFI IC
Type-C USB
4MB Flash
2MB PSRAM
27xIO
ADC, DAC, I2C, SPI, UART, USB OTG
Compatible with LOLIN D1 mini shields
Compatible with MicroPython, and ESP-IDF
Default firmware: MicroPython

**Comment by BoraSchninsky** [comment]
I have tried to compile the source code in platformio but a error is in it.. can you compile it for the board?

Many thanks

**Comment by vr6syncro** [comment]
Untested! It compiled in my software without issues. Here a image and files for flashing. But i dont know if OTA updates will work after it flashed sucessful. 

![s2_mini_v1 0 0_4_16x9](https://github.com/vr6syncro/Bambulab_Esp32_LEDController/assets/27892314/b6b98b4d-e3d2-45c5-b590-d5ae8c6a7241)
[lolin_s2_mini.zip](https://github.com/vr6syncro/Bambulab_Esp32_LEDController/files/12776736/lolin_s2_mini.zip)

So if it is not working i cant test it because i dont have this board. Please use the supported one.

**Comment by BoraSchninsky** [comment]
Mannnny thanks.. good guy

**Comment by BoraSchninsky** [comment]
Now the board is running but whiteout mqtt..
And my second stripe on the right is not light up.

Thank you. I must show 
![IMG_20231001_191711](https://github.com/vr6syncro/Bambulab_Esp32_LEDController/assets/49289734/2cda3d0e-f0a0-4ce2-9df4-c66816a458aa)

**Comment by vr6syncro** [comment]
slicer say heating bed... display show heating bed... connection and mqtt is ok... second strip maybe wrong soldered?

**Comment by BoraSchninsky** [comment]
No .. soldering is ok ... I have it new soldered from ground up.. with new leds.

I don't know... ![IMG_20231014_190043.jpg](https://github.com/vr6syncro/Bambulab_Esp32_LEDController/assets/49289734/aeceb69a-bc0a-45ef-8c9a-0c5c9d2c027b)

![IMG_20231014_190012.jpg](https://github.com/vr6syncro/Bambulab_Esp32_LEDController/assets/49289734/7a1e66f2-01c9-416c-a7de-cd385915303f)

![IMG_20231014_185953.jpg](https://github.com/vr6syncro/Bambulab_Esp32_LEDController/assets/49289734/12aaf6fe-585a-4602-bacb-2a32ad15c637)

**Comment by BoraSchninsky** [comment]
![IMG_20231014_185953~2.jpg](https://github.com/vr6syncro/Bambulab_Esp32_LEDController/assets/49289734/13ceef7a-491f-4694-a8ca-1f42d1e9128f)

Now I looks good the stripe was in wrong direction.. jippi


![IMG_20231014_191807.jpg](https://github.com/vr6syncro/Bambulab_Esp32_LEDController/assets/49289734/5768f4f0-43dd-4ee7-b93a-062160b824d2)

**Comment by vr6syncro** [comment]
DIN - DOUT wrong... common mistake ;)  Nice to hear that it's working now
