### ISSUE TITLE
LED Beleuchtung für Druckbett

### ISSUE THREAD

**Issue by Billiboy71** [vr6syncro/Bambulab_Esp32_LEDController#7]
Auf der Suche nach eine Druckerbeleuchtung bin ich über Euer Projekt gestolpert. Vielen Dank, das ist super. 
könnte man das irgendwie abändern das man das wie in diesem Projekt macht. Mich stören dort die RGBWW LED Streifen, Neopixel sind viel cooler.
https://github.com/DutchDevelop/BambulabLedController

**Comment by vr6syncro** [comment]
Update auf die V3 und teste den Strip Mode... https://github.com/vr6syncro/Bambulab_Esp32_LEDController/wiki/Strip-Mode

Falls du aber andere Farben haben willst musst du deine Firmware selber compilieren 
https://github.com/vr6syncro/Bambulab_Esp32_LEDController/blob/main/src/ledhandle_stripe_case.h
